# Generated by Django 4.2.4 on 2023-10-04 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='card',
            name='imagem',
        ),
        migrations.AddField(
            model_name='card',
            name='codigo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='conclusao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='descricao_codigo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='imagem_card',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='card',
            name='imagem_circuito',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='card',
            name='imagem_principal_conteudo',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='card',
            name='introducao',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='MateriaisExperimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('card', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iot.card')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passo_a_passo_circuito', models.CharField(max_length=100)),
                ('card', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iot.card')),
            ],
        ),
    ]
