# Generated by Django 4.2.4 on 2023-09-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='imagem',
            new_name='imagem_card',
        ),
        migrations.AddField(
            model_name='card',
            name='imagem_conteudo',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
    ]
