# Generated by Django 4.2.4 on 2023-10-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_remove_card_descricao_remove_card_imagem_card_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemDeContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
