# Generated by Django 4.2.4 on 2023-09-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_alter_card_imagem_card_alter_card_imagem_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='imagem_card',
            field=models.ImageField(upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='imagem_conteudo',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
    ]
