# Generated by Django 4.2.4 on 2023-11-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_mensagemdecontato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='favorito',
        ),
    ]
