# Generated by Django 4.2.4 on 2023-09-16 21:59

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_card_conteudo_alter_card_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='conteudo',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
