# Generated by Django 4.2.4 on 2023-09-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_alter_card_conteudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='conteudo',
            new_name='conteudo_markdown',
        ),
    ]
