# Generated by Django 4.2.4 on 2023-09-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_rename_conteudo_card_conteudo_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='conteudo_markdown',
        ),
        migrations.AddField(
            model_name='card',
            name='conteudo',
            field=models.TextField(default=''),
        ),
    ]
