# Generated by Django 4.2.4 on 2023-09-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_remove_card_conteudo_markdown_card_conteudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='conteudo',
            new_name='circuito',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='imagem_conteudo',
            new_name='imagem_circuito',
        ),
        migrations.RemoveField(
            model_name='card',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='card',
            name='imagem_card',
        ),
        migrations.AddField(
            model_name='card',
            name='bibliotecas',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='codigo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='conclusao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='imagem_principal',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='card',
            name='introducao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='materiais_necessarios',
            field=models.TextField(default=''),
        ),
    ]
