# Generated by Django 4.2.4 on 2023-09-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_rename_conteudo_card_circuito_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='imagem_principal',
            new_name='imagem_card',
        ),
        migrations.AddField(
            model_name='card',
            name='imagem_principal_conteudo',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
    ]
