# Generated by Django 4.2.4 on 2023-09-16 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_rename_imagem_principal_card_imagem_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='circuito',
        ),
        migrations.RemoveField(
            model_name='card',
            name='imagem_circuito',
        ),
        migrations.RemoveField(
            model_name='card',
            name='materiais_necessarios',
        ),
        migrations.CreateModel(
            name='MateriaisExperimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('card', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iot.card')),
            ],
        ),
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='cards/')),
                ('item_circuito', models.CharField(max_length=100)),
                ('card', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iot.card')),
            ],
        ),
    ]
