# Generated by Django 4.2.4 on 2023-09-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_remove_card_circuito_remove_card_imagem_circuito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuito',
            name='imagem',
        ),
        migrations.AddField(
            model_name='card',
            name='imagem_cirtuito',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
    ]
