# Generated by Django 4.2.4 on 2023-09-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_remove_circuito_imagem_card_imagem_cirtuito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuito',
            old_name='item_circuito',
            new_name='passo_a_passo_circuito',
        ),
    ]
