# Generated by Django 4.2.4 on 2023-09-16 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0013_rename_item_circuito_circuito_passo_a_passo_circuito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='imagem_cirtuito',
            new_name='imagem_circuito',
        ),
    ]
