# Generated by Django 4.2.4 on 2023-09-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0014_rename_imagem_cirtuito_card_imagem_circuito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='bibliotecas',
        ),
        migrations.AddField(
            model_name='card',
            name='descricao_codigo',
            field=models.TextField(default=''),
        ),
    ]
