# Generated by Django 4.2.4 on 2023-09-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0016_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
