# Generated by Django 4.2.4 on 2023-09-24 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot', '0017_card_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='favorito',
        ),
        migrations.AddField(
            model_name='card',
            name='favorito_por',
            field=models.ManyToManyField(blank=True, related_name='cards_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
