# Generated by Django 4.2.4 on 2023-09-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0018_remove_card_favorito_card_favorito_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='favorito_por',
        ),
        migrations.AddField(
            model_name='card',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
